#!/bin/sh
echo ""
echo "**** Test command"
echo ""
if [ $# -eq 0 ]
then 
   echo "no parameter"
else
   export serial=$1
   stringlen=${#serial}
   substring=$(echo $serial | cut -c1-5)
   substringok="S182V"
   echo "serial        = " $serial
   echo "serial lenght = " $stringlen
   echo "substring     = " $substring
   echo ""
   if [ $stringlen -eq 13 ] && [ $substring = $substringok ]
   then 
      echo "serial lenght ok (${#serial})"
      echo "serial start with S182V = OK"
   else
      if [ $stringlen != 13 ]
      then
         echo "Serial lenght not right. Should be 13 characters."
      fi
      if [ $substring != $substringok ]
      then
         echo "Serial start not right. Should be start with '"$substringok"'."
      fi
   fi
fi
echo ""

