#!/bin/sh
rm -rf $1

for nameserver in $new_domain_name_servers; do
	echo nameserver=$nameserver >> $1 
done
if [ -n "$new_domain_name" ] ; then
	echo dnsname=$new_domain_name >> $1
fi
if [ -n "$dslite_name" ] ; then
	echo dslite_name=$dslite_name >> $1
fi
