include $(TOPDIR)/rules.mk

PKG_NAME:=firmware-version

PKG_VERSION:=20181217
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk

define Package/firmware-version
  SECTION:=release
  CATEGORY:=Zyxel Packages
  TITLE:=System firmware ABI version
  URL:=http://www.zyxel.com/
endef

define Package/firmware-version/description
System firmware ABI version
endef

define Build/Configure
endef

define Build/Compile
endef

define Package/firmware-version/install
	:
endef

$(eval $(call BuildPackage,firmware-version))
