#ifndef _ZCFG_RDM_OID_H
#define _ZCFG_RDM_OID_H

#define RDM_OID_DEVICE                           0 	/*Device*/
#define RDM_OID_SERVICE                          108	/*Device.Services*/
#define RDM_OID_PACKAGE                          144	/*Device.Services.X_ZYXEL_Package.i*/
#define RDM_OID_PACKAGE_INSTALL                  372	/*Device.Services.X_ZYXEL_Package_Install*/
#define RDM_OID_VOICE_SRV                        456	/*Device.Services.VoiceService.i*/
#define RDM_OID_VOICE_CAPB                       540	/*Device.Services.VoiceService.i.Capabilities*/
#define RDM_OID_VOICE_CAPB_SIP                   1344	/*Device.Services.VoiceService.i.Capabilities.SIP*/
#define RDM_OID_VOICE_CAPB_MGCP                  1644	/*Device.Services.VoiceService.i.Capabilities.MGCP*/
#define RDM_OID_VOICE_CAPB_H323                  1704	/*Device.Services.VoiceService.i.Capabilities.H323*/
#define RDM_OID_VOICE_CAPB_CODEC                 1788	/*Device.Services.VoiceService.i.Capabilities.Codec.i*/
#define RDM_OID_VOICE_PROF                       1968	/*Device.Services.VoiceService.i.VoiceProfile.i*/
#define RDM_OID_VOICE_PROF_SRV_PRO_INFO          3036	/*Device.Services.VoiceService.i.VoiceProfile.i.ServiceProviderInfo*/
#define RDM_OID_VOICE_PROF_SIP                   3168	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP*/
#define RDM_OID_VOICE_PROF_SIP_SUBSCRIBE_OBJ     4764	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_PROF_SIP_RESP_MAP_OBJ      4920	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.ResponseMap.i*/
#define RDM_OID_VOICE_PROF_RTP                   5028	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP*/
#define RDM_OID_VOICE_PROF_RTP_RTCP              5208	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.RTCP*/
#define RDM_OID_VOICE_PROF_RTP_SRTP              5316	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.SRTP*/
#define RDM_OID_VOICE_PROF_RTP_REDUNDANCY        5448	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.Redundancy*/
#define RDM_OID_VOICE_PROF_NUM_PLAN              5676	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan*/
#define RDM_OID_VOICE_PROF_NUM_PLAN_PREFIX_INFO  5928	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan.PrefixInfo.i*/
#define RDM_OID_VOICE_PROF_TONE                  6156	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone*/
#define RDM_OID_VOICE_PROF_TONE_EVENT            6264	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Event.i*/
#define RDM_OID_VOICE_PROF_TONE_DESCRIPTION      6348	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Description.i*/
#define RDM_OID_VOICE_PROF_TONE_PATTERN          6552	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Pattern.i*/
#define RDM_OID_VOICE_PROF_FAX_T38               6924	/*Device.Services.VoiceService.i.VoiceProfile.i.FaxT38*/
#define RDM_OID_VOICE_LINE                       7104	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i*/
#define RDM_OID_VOICE_LINE_SIP                   7476	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP*/
#define RDM_OID_VOICE_LINE_SIP_EVENT_SUBS        7752	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_LINE_RINGER                7860	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer*/
#define RDM_OID_VOICE_LINE_RINGER_EVENT          7968	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Event.i*/
#define RDM_OID_VOICE_LINE_RINGER_DESCRIPTION    8052	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Description.i*/
#define RDM_OID_VOICE_LINE_RINGER_PATTERN        8208	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Pattern.i*/
#define RDM_OID_VOICE_LINE_CALLING_FEATURE       8340	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.CallingFeatures*/
#define RDM_OID_VOICE_LINE_PROCESSING            9840	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.VoiceProcessing*/
#define RDM_OID_VOICE_LINE_CODEC                 9996	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec*/
#define RDM_OID_VOICE_LINE_CODEC_LIST            10200	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec.List.i*/
#define RDM_OID_VOICE_LINE_SESSION               10476	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Session.i*/
#define RDM_OID_VOICE_LINE_STATS                 10632	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Stats*/
#define RDM_OID_VOICE_PHY_INTF                   11412	/*Device.Services.VoiceService.i.PhyInterface.i*/
#define RDM_OID_VOICE_PSTN                       12072	/*Device.Services.VoiceService.i.X_ZYXEL_PSTN.i*/
#define RDM_OID_VOICE_COMMON                     12252	/*Device.Services.VoiceService.i.X_ZYXEL_Common*/
#define RDM_OID_VOICE_PHONE_BOOK                 12792	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook*/
#define RDM_OID_SPEED_DIAL_BOOK                  12828	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook*/
#define RDM_OID_SPEED_DIAL_BOOK_LIST             12888	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook.List.i*/
#define RDM_OID_CALL_POLICY_BOOK                 13068	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook*/
#define RDM_OID_CALL_POLICY_BOOK_LIST            13152	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook.List.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK 13332	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_IF_LIST 13392	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_PORT_LIST 13476	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i.PortList.i*/
#define RDM_OID_VOICE_FXO                        13536	/*Device.Services.VoiceService.i.X_ZYXEL_FXO*/
#define RDM_OID_VOICE_FXO_PORT                   13596	/*Device.Services.VoiceService.i.X_ZYXEL_FXO.Port.i*/
#define RDM_OID_VOICE_DECT                       13872	/*Device.Services.VoiceService.i.X_ZYXEL_DECT*/
#define RDM_OID_VOICE_DECT_B_S                   13932	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.BaseStation*/
#define RDM_OID_VOICE_DECT_H_S                   14424	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.Handset.i*/
#define RDM_OID_VOICE_CALL_STATUS                14748	/*Device.Services.VoiceService.i.X_ZYXEL_CALL_STATUS*/
#define RDM_OID_DEV_INFO                         14976	/*Device.DeviceInfo*/
#define RDM_OID_DEV_INFO_VEND_CONF_FILE          15564	/*Device.DeviceInfo.VendorConfigFile.i*/
#define RDM_OID_DEV_INFO_SUP_DATA_MODEL          15720	/*Device.DeviceInfo.SupportedDataModel.i*/
#define RDM_OID_DEV_INFO_MEM_STAT                15852	/*Device.DeviceInfo.MemoryStatus*/
#define RDM_OID_DEV_INFO_PS_STAT                 15936	/*Device.DeviceInfo.ProcessStatus*/
#define RDM_OID_DEV_INFO_PS_STAT_PS              16020	/*Device.DeviceInfo.ProcessStatus.Process.i*/
#define RDM_OID_TEMP_STAT                        16200	/*Device.DeviceInfo.TemperatureStatus*/
#define RDM_OID_TEMP_STAT_TEMP_SENSOR            16260	/*Device.DeviceInfo.TemperatureStatus.TemperatureSensor.i*/
#define RDM_OID_NETWORK_PROP                     16704	/*Device.DeviceInfo.NetworkProperties.i*/
#define RDM_OID_DEV_INFO_PROCESSOR               16788	/*Device.DeviceInfo.Processor.i*/
#define RDM_OID_DEV_INFO_VENDOR_LOG_FILE         16872	/*Device.DeviceInfo.VendorLogFile.i*/
#define RDM_OID_DEV_INFO_PROXIER_INFO            17004	/*Device.DeviceInfo.ProxierInfo.i*/
#define RDM_OID_DEV_INFO_LOC                     17136	/*Device.DeviceInfo.Location.i*/
#define RDM_OID_DEV_INFO_POWER_STAT              17292	/*Device.DeviceInfo.X_ZYXEL_PowerStatus*/
#define RDM_OID_MGMT_SRV                         17376	/*Device.ManagementServer*/
#define RDM_OID_MGMT_SRV_MGAB_DEV                19356	/*Device.ManagementServer.ManageableDevice.i*/
#define RDM_OID_MGMT_SRV_AUTO_TRANS_COMPLETE_POL 19536	/*Device.ManagementServer.AutonomousTransferCompletePolicy*/
#define RDM_OID_MGMT_SRV_DL_AVAIL                19668	/*Device.ManagementServer.DownloadAvailability*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT        19704	/*Device.ManagementServer.DownloadAvailability.Announcement*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT_GROUP  19812	/*Device.ManagementServer.DownloadAvailability.Announcement.Group.i*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_QUERY          19944	/*Device.ManagementServer.DownloadAvailability.Query*/
#define RDM_OID_MGMT_SRV_DU_STATE_CHANGE_COMPL_POL 20052	/*Device.ManagementServer.DUStateChangeComplPolicy*/
#define RDM_OID_MGMT_SRV_EMBEDED_DEV             20184	/*Device.ManagementServer.EmbeddedDevice.i*/
#define RDM_OID_MGMT_SRV_VIRTUAL_DEV             20436	/*Device.ManagementServer.VirtualDevice.i*/
#define RDM_OID_GATEWAY_INFO                     20592	/*Device.GatewayInfo*/
#define RDM_OID_TIME                             20700	/*Device.Time*/
#define RDM_OID_USR_INTF                         21360	/*Device.UserInterface*/
#define RDM_OID_USR_INTF_REMO_ACESS              21972	/*Device.UserInterface.RemoteAccess*/
#define RDM_OID_USR_INTF_LOCAL_DISP              22104	/*Device.UserInterface.LocalDisplay*/
#define RDM_OID_IFACE_STACK                      22332	/*Device.InterfaceStack.i*/
#define RDM_OID_DSL                              22488	/*Device.DSL*/
#define RDM_OID_DSL_LINE                         22596	/*Device.DSL.Line.i*/
#define RDM_OID_DSL_LINE_ST                      26784	/*Device.DSL.Line.i.Stats*/
#define RDM_OID_DSL_LINE_ST_TOTAL                27132	/*Device.DSL.Line.i.Stats.Total*/
#define RDM_OID_DSL_LINE_ST_SHOWTIME             27864	/*Device.DSL.Line.i.Stats.Showtime*/
#define RDM_OID_DSL_LINE_ST_LAST_SHOWTIME        28404	/*Device.DSL.Line.i.Stats.LastShowtime*/
#define RDM_OID_DSL_LINE_ST_LAST_CUR_DAY         28488	/*Device.DSL.Line.i.Stats.CurrentDay*/
#define RDM_OID_DSL_LINE_ST_LAST_QUAR_HR         28980	/*Device.DSL.Line.i.Stats.QuarterHour*/
#define RDM_OID_DSL_LINE_TEST_PARAMS             29064	/*Device.DSL.Line.i.TestParams*/
#define RDM_OID_DSL_CHANNEL                      29628	/*Device.DSL.Channel.i*/
#define RDM_OID_DSL_CHANNEL_ST                   30144	/*Device.DSL.Channel.i.Stats*/
#define RDM_OID_DSL_CHANNEL_ST_TOTAL             30492	/*Device.DSL.Channel.i.Stats.Total*/
#define RDM_OID_DSL_CHANNEL_ST_SHOWTIME          30672	/*Device.DSL.Channel.i.Stats.Showtime*/
#define RDM_OID_DSL_CHANNEL_ST_LAST_SHOWTIME     30852	/*Device.DSL.Channel.i.Stats.LastShowtime*/
#define RDM_OID_DSL_CHANNEL_ST_CUR_DAY           31032	/*Device.DSL.Channel.i.Stats.CurrentDay*/
#define RDM_OID_DSL_CHANNEL_ST_QUAR_HR           31212	/*Device.DSL.Channel.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP                      31392	/*Device.DSL.BondingGroup.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL       31908	/*Device.DSL.BondingGroup.i.BondedChannel.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH   31992	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH_ST 32028	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet.Stats*/
#define RDM_OID_DSL_BOND_GP_ST                   32256	/*Device.DSL.BondingGroup.i.Stats*/
#define RDM_OID_DSL_BOND_GP_ST_TOTAL             32724	/*Device.DSL.BondingGroup.i.Stats.Total*/
#define RDM_OID_DSL_BOND_GP_ST_CURRENT_DAY       33024	/*Device.DSL.BondingGroup.i.Stats.CurrentDay*/
#define RDM_OID_DSL_BOND_GP_ST_QTR_HR            33324	/*Device.DSL.BondingGroup.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP_ETH                  33624	/*Device.DSL.BondingGroup.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_ETH_ST               33660	/*Device.DSL.BondingGroup.i.Ethernet.Stats*/
#define RDM_OID_DSL_DIAG                         34080	/*Device.DSL.Diagnostics*/
#define RDM_OID_DSL_DIAG_ADSL_LINE_TEST          34116	/*Device.DSL.Diagnostics.ADSLLineTest*/
#define RDM_OID_OPT                              35016	/*Device.Optical*/
#define RDM_OID_OPT_INTF                         35076	/*Device.Optical.Interface.i*/
#define RDM_OID_OPT_INTF_ST                      35424	/*Device.Optical.Interface.i.Stats*/
#define RDM_OID_ATM                              35652	/*Device.ATM*/
#define RDM_OID_ATM_LINK                         35712	/*Device.ATM.Link.i*/
#define RDM_OID_ATM_LINK_ST                      36252	/*Device.ATM.Link.i.Stats*/
#define RDM_OID_ATM_LINK_QOS                     36864	/*Device.ATM.Link.i.QoS*/
#define RDM_OID_ATM_DIAG                         37020	/*Device.ATM.Diagnostics*/
#define RDM_OID_ATM_DIAG_F5_LO                   37056	/*Device.ATM.Diagnostics.F5Loopback*/
#define RDM_OID_ATM_DIAG_F4_LO                   37356	/*Device.ATM.Diagnostics.X_ZYXEL_F4Loopback*/
#define RDM_OID_PTM                              37656	/*Device.PTM*/
#define RDM_OID_PTM_LINK                         37716	/*Device.PTM.Link.i*/
#define RDM_OID_PTM_LINK_ST                      38280	/*Device.PTM.Link.i.Stats*/
#define RDM_OID_ETH                              38796	/*Device.Ethernet*/
#define RDM_OID_ETH_RMON_ST                      38928	/*Device.Ethernet.RMONStats.i*/
#define RDM_OID_ETH_IFACE                        39492	/*Device.Ethernet.Interface.i*/
#define RDM_OID_ETH_INTF_ST                      39960	/*Device.Ethernet.Interface.i.Stats*/
#define RDM_OID_ETH_LINK                         40356	/*Device.Ethernet.Link.i*/
#define RDM_OID_ETH_LINK_ST                      40680	/*Device.Ethernet.Link.i.Stats*/
#define RDM_OID_ETH_VLAN_TERM                    41076	/*Device.Ethernet.VLANTermination.i*/
#define RDM_OID_ETH_VLAN_TERM_ST                 41376	/*Device.Ethernet.VLANTermination.i.Stats*/
#define RDM_OID_USB                              41772	/*Device.USB*/
#define RDM_OID_USB_INTF                         41856	/*Device.USB.Interface.i*/
#define RDM_OID_USB_INTF_STAT                    42156	/*Device.USB.Interface.i.Stats*/
#define RDM_OID_USB_PORT                         42552	/*Device.USB.Port.i*/
#define RDM_OID_USB_USBHOSTS                     42780	/*Device.USB.USBHosts*/
#define RDM_OID_USB_USBHOSTS_HOST                42840	/*Device.USB.USBHosts.Host.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV            43068	/*Device.USB.USBHosts.Host.i.Device.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_PAR        43584	/*Device.USB.USBHosts.Host.i.Device.i.X_ZYXEL_Partition.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG        43740	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG_INTF   43824	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i.Interface.i*/
#define RDM_OID_CELLULAR                         43956	/*Device.Cellular*/
#define RDM_OID_CELLULAR_INTERFACE               44064	/*Device.Cellular.Interface.i*/
#define RDM_OID_CELLULAR_IFACE_U_S_I_M           44412	/*Device.Cellular.Interface.i.USIM*/
#define RDM_OID_CELLULAR_ACCESS_POINT            44520	/*Device.Cellular.AccessPoint.i*/
#define RDM_OID_HPNA                             44748	/*Device.HPNA*/
#define RDM_OID_HPNA_INTF                        44808	/*Device.HPNA.Interface.i*/
#define RDM_OID_HPNA_INTF_ST                     45492	/*Device.HPNA.Interface.i.Stats*/
#define RDM_OID_HPNA_INTF_QOS                    45888	/*Device.HPNA.Interface.i.QoS*/
#define RDM_OID_HPNA_INTF_QOS_FLOW_SPEC          45948	/*Device.HPNA.Interface.i.QoS.FlowSpec.i*/
#define RDM_OID_HPNA_INTF_ASSOC_DEV              46320	/*Device.HPNA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HPNA_DIAG                        46548	/*Device.HPNA.Diagnostics*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT         46584	/*Device.HPNA.Diagnostics.PHYThroughput*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT_RESULT  46860	/*Device.HPNA.Diagnostics.PHYThroughput.Result.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONT              47064	/*Device.HPNA.Diagnostics.PerformanceMonitoring*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES     47172	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES_NODE 47280	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes.Node.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS  47916	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS_CHANNEL 48000	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels.Channel.i*/
#define RDM_OID_MOCA                             48300	/*Device.MoCA*/
#define RDM_OID_MOCA_INTF                        48360	/*Device.MoCA.Interface.i*/
#define RDM_OID_MOCA_INTF_ST                     49260	/*Device.MoCA.Interface.i.Stats*/
#define RDM_OID_MOCA_INTF_QOS                    49656	/*Device.MoCA.Interface.i.QoS*/
#define RDM_OID_MOCA_INTF_QOS_FLOW_ST            49764	/*Device.MoCA.Interface.i.QoS.FlowStats.i*/
#define RDM_OID_MOCA_INTF_ASSOC_DEV              49944	/*Device.MoCA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_GHN                              50388	/*Device.Ghn*/
#define RDM_OID_GHN_INTF                         50448	/*Device.Ghn.Interface.i*/
#define RDM_OID_GHN_INTF_ST                      51012	/*Device.Ghn.Interface.i.Stats*/
#define RDM_OID_GHN_INTF_ASSOC_DEV               51408	/*Device.Ghn.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HOME_PLUG                        51564	/*Device.Homeplug*/
#define RDM_OID_HOMEPLUG_INTF                    51624	/*Device.Homeplug.Interface.i*/
#define RDM_OID_HOMEPLUG_INTF_ST                 52044	/*Device.Homeplug.Interface.i.Stats*/
#define RDM_OID_HOMEPLUG_INTF_ASSOC_DEV          52560	/*Device.Homeplug.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA                              52764	/*Device.UPA*/
#define RDM_OID_UPA_INTF                         52824	/*Device.UPA.Interface.i*/
#define RDM_OID_UPA_INTF_ST                      53364	/*Device.UPA.Interface.i.Stats*/
#define RDM_OID_UPA_INTF_ASSOC_DEV               53760	/*Device.UPA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA_INTF_ACTIVE_NOTCH            54060	/*Device.UPA.Interface.i.ActiveNotch.i*/
#define RDM_OID_UPA_INTF_BRIDGE_FOR              54216	/*Device.UPA.Interface.i.BridgeFor.i*/
#define RDM_OID_UPA_DIAG                         54324	/*Device.UPA.Diagnostics*/
#define RDM_OID_UPA_DIAG_INTF_MEASUREMENT        54360	/*Device.UPA.Diagnostics.InterfaceMeasurement*/
#define RDM_OID_WIFI                             54540	/*Device.WiFi*/
#define RDM_OID_WIFI_ONE_SSID                    54744	/*Device.WiFi.X_ZYXEL_OneSSID*/
#define RDM_OID_WIFI_RADIO                       54804	/*Device.WiFi.Radio.i*/
#define RDM_OID_WIFI_RADIO_ST                    56592	/*Device.WiFi.Radio.i.Stats*/
#define RDM_OID_WIFI_SSID                        56844	/*Device.WiFi.SSID.i*/
#define RDM_OID_WIFI_SSID_STAT                   57552	/*Device.WiFi.SSID.i.Stats*/
#define RDM_OID_WIFI_ACCESS_POINT                57948	/*Device.WiFi.AccessPoint.i*/
#define RDM_OID_WIFI_ACCESS_POINT_SEC            58320	/*Device.WiFi.AccessPoint.i.Security*/
#define RDM_OID_WIFI_ACCESS_POINT_ACCOUNTING     59364	/*Device.WiFi.AccessPoint.i.Accounting*/
#define RDM_OID_WIFI_ACCESS_POINT_WPS            59592	/*Device.WiFi.AccessPoint.i.WPS*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV      60036	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV_ST   60312	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i.Stats*/
#define RDM_OID_WIFI_STA_FILTER                  60564	/*Device.WiFi.AccessPoint.i.StationFilter*/
#define RDM_OID_WIFI_END_POINT                   60648	/*Device.WiFi.EndPoint.i*/
#define RDM_OID_WIFI_END_POINT_ST                60828	/*Device.WiFi.EndPoint.i.Stats*/
#define RDM_OID_WIFI_END_POINT_SEC               60960	/*Device.WiFi.EndPoint.i.Security*/
#define RDM_OID_WIFI_END_POINT_PROFILE           61020	/*Device.WiFi.EndPoint.i.Profile.i*/
#define RDM_OID_WIFI_END_POINT_PROFILE_SEC       61200	/*Device.WiFi.EndPoint.i.Profile.i.Security*/
#define RDM_OID_WPS                              61332	/*Device.WiFi.EndPoint.i.WPS*/
#define RDM_OID_WIFI_DIAGNOSTIC                  61440	/*Device.WiFi.NeighboringWiFiDiagnostic*/
#define RDM_OID_WIFI_DIAGNOSTIC_RESULTS          61548	/*Device.WiFi.NeighboringWiFiDiagnostic.Result.i*/
#define RDM_OID_WIFI_AP_STEERING                 61992	/*Device.WiFi.X_ZYXEL_ApSteering*/
#define RDM_OID_WLAN_SCHEDULER                   62436	/*Device.WiFi.X_ZYXEL_WLAN_Scheduler.i*/
#define RDM_OID_BRIDGING                         62760	/*Device.Bridging*/
#define RDM_OID_BRIDGING_BR                      63036	/*Device.Bridging.Bridge.i*/
#define RDM_OID_BRIDGING_BR_PORT                 63360	/*Device.Bridging.Bridge.i.Port.i*/
#define RDM_OID_BRIDGING_BR_PORT_ST              63828	/*Device.Bridging.Bridge.i.Port.i.Stats*/
#define RDM_OID_BRIDGING_BR_VLAN                 64224	/*Device.Bridging.Bridge.i.VLAN.i*/
#define RDM_OID_BRIDGING_BR_VLANPORT             64356	/*Device.Bridging.Bridge.i.VLANPort.i*/
#define RDM_OID_BRIDGING_FILTER                  64512	/*Device.Bridging.Filter.i*/
#define RDM_OID_PPP                              65340	/*Device.PPP*/
#define RDM_OID_PPP_IFACE                        65424	/*Device.PPP.Interface.i*/
#define RDM_OID_PPP_IFACE_PPPOA                  66372	/*Device.PPP.Interface.i.PPPoA*/
#define RDM_OID_PPP_IFACE_PPPOE                  66408	/*Device.PPP.Interface.i.PPPoE*/
#define RDM_OID_PPP_IFACE_IPCP                   66540	/*Device.PPP.Interface.i.IPCP*/
#define RDM_OID_PPP_INTF_IPV6CP                  66696	/*Device.PPP.Interface.i.IPV6CP*/
#define RDM_OID_PPP_IFACE_STAT                   66780	/*Device.PPP.Interface.i.Stats*/
#define RDM_OID_IP                               67176	/*Device.IP*/
#define RDM_OID_IP_IFACE                         67428	/*Device.IP.Interface.i*/
#define RDM_OID_IP_IFACE_V4_ADDR                 68928	/*Device.IP.Interface.i.IPv4Address.i*/
#define RDM_OID_IP_IFACE_V6_ADDR                 69180	/*Device.IP.Interface.i.IPv6Address.i*/
#define RDM_OID_IP_IFACE_V6_PREFIX               69552	/*Device.IP.Interface.i.IPv6Prefix.i*/
#define RDM_OID_IP_IFACE_STAT                    69996	/*Device.IP.Interface.i.Stats*/
#define RDM_OID_IP_ACTIVE_PORT                   70392	/*Device.IP.ActivePort.i*/
#define RDM_OID_IP_DIAG                          70548	/*Device.IP.Diagnostics*/
#define RDM_OID_IP_DIAG_IPPING                   70584	/*Device.IP.Diagnostics.IPPing*/
#define RDM_OID_IP_DIAG_TRACE_RT                 71028	/*Device.IP.Diagnostics.TraceRoute*/
#define RDM_OID_IP_DIAG_TRACERT_RT_HOPS          71352	/*Device.IP.Diagnostics.TraceRoute.RouteHops.i*/
#define RDM_OID_IP_DIAG_DL_DIAG                  71484	/*Device.IP.Diagnostics.DownloadDiagnostics*/
#define RDM_OID_IP_DIAG_UL_DIAG                  71976	/*Device.IP.Diagnostics.UploadDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_CFG             72420	/*Device.IP.Diagnostics.UDPEchoConfig*/
#define RDM_OID_IP_DIAG_UDP_ECHO_DIAG            72744	/*Device.IP.Diagnostics.UDPEchoDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_PAK_RST         73260	/*Device.IP.Diagnostics.UDPEchoDiagnostics.IndividualPacketResult.i*/
#define RDM_OID_IP_DIAG_SVR_SELECT_DIAG          73488	/*Device.IP.Diagnostics.ServerSelectionDiagnostics*/
#define RDM_OID_IPSEC                            73812	/*Device.IPsec*/
#define RDM_OID_IPSEC_STAT                       74304	/*Device.IPsec.Stats*/
#define RDM_OID_IPSEC_FILTER                     74628	/*Device.IPsec.Filter.i*/
#define RDM_OID_IPSEC_PROFILE                    75624	/*Device.IPsec.Profile.i*/
#define RDM_OID_IPSEC_PROFILE_SENT_CP_ATTR       76884	/*Device.IPsec.Profile.i.SentCPAttr.i*/
#define RDM_OID_IPSEC_TUNNEL                     77016	/*Device.IPsec.Tunnel.i*/
#define RDM_OID_IPSEC_TUNNEL_STAT                77748	/*Device.IPsec.Tunnel.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA                    77904	/*Device.IPsec.IKEv2SA.i*/
#define RDM_OID_IPSEC_IKEV2SA_STAT               78252	/*Device.IPsec.IKEv2SA.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA_RECEIVED_CP_ATTR   78480	/*Device.IPsec.IKEv2SA.i.ReceivedCPAttr.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA           78564	/*Device.IPsec.IKEv2SA.i.ChildSA.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA_STAT      78720	/*Device.IPsec.IKEv2SA.i.ChildSA.i.Stats*/
#define RDM_OID_ZY_IPSEC_XML_RELOAD              78996	/*Device.IPsec.X_ZYXEL_XML_Reload*/
#define RDM_OID_GRE                              79056	/*Device.GRE*/
#define RDM_OID_GRE_TUNNEL                       79140	/*Device.GRE.Tunnel.i*/
#define RDM_OID_GRE_TUNNEL_STAT                  79656	/*Device.GRE.Tunnel.i.Stats*/
#define RDM_OID_GRE_TUNNEL_IFACE                 79932	/*Device.GRE.Tunnel.i.Interface.i*/
#define RDM_OID_GRE_TUNNEL_IFACE_STAT            80232	/*Device.GRE.Tunnel.i.Interface.i.Stats*/
#define RDM_OID_GRE_FILTER                       80460	/*Device.GRE.Filter.i*/
#define RDM_OID_CAPT_PORTAL                      80712	/*Device.CaptivePortal*/
#define RDM_OID_ROUTING                          80844	/*Device.Routing*/
#define RDM_OID_ROUTING_ROUTER                   80904	/*Device.Routing.Router.i*/
#define RDM_OID_ROUTING_ROUTER_V4_FWD            81132	/*Device.Routing.Router.i.IPv4Forwarding.i*/
#define RDM_OID_ROUTING_ROUTER_V6_FWD            81648	/*Device.Routing.Router.i.IPv6Forwarding.i*/
#define RDM_OID_ROUTING_RIP                      81924	/*Device.Routing.RIP*/
#define RDM_OID_ROUTING_RIP_INTF_SET             82032	/*Device.Routing.RIP.InterfaceSetting.i*/
#define RDM_OID_ROUTING_RT_INFO                  82284	/*Device.Routing.RouteInformation*/
#define RDM_OID_ROUTING_RT_INFO_INTF_SET         82368	/*Device.Routing.RouteInformation.InterfaceSetting.i*/
#define RDM_OID_NEIGHBOR_DISCOVERY               82644	/*Device.NeighborDiscovery*/
#define RDM_OID_NEIGHBOR_DISCOVERY_INTF_SET      82728	/*Device.NeighborDiscovery.InterfaceSetting.i*/
#define RDM_OID_RT_ADV                           83028	/*Device.RouterAdvertisement*/
#define RDM_OID_RT_ADV_INTF_SET                  83112	/*Device.RouterAdvertisement.InterfaceSetting.i*/
#define RDM_OID_RT_ADV_INTF_SET_OPT              83700	/*Device.RouterAdvertisement.InterfaceSetting.i.Option.i*/
#define RDM_OID_IPV6RD                           83832	/*Device.IPv6rd*/
#define RDM_OID_IPV6RD_INTF                      83916	/*Device.IPv6rd.InterfaceSetting.i*/
#define RDM_OID_DS_LITE                          84216	/*Device.DSLite*/
#define RDM_OID_DS_LITE_INTF_SET                 84300	/*Device.DSLite.InterfaceSetting.i*/
#define RDM_OID_QOS                              84648	/*Device.QoS*/
#define RDM_OID_QOS_CLS                          85260	/*Device.QoS.Classification.i*/
#define RDM_OID_QOS_APP                          87384	/*Device.QoS.App.i*/
#define RDM_OID_QOS_FLOW                         87660	/*Device.QoS.Flow.i*/
#define RDM_OID_QOS_POLICER                      87984	/*Device.QoS.Policer.i*/
#define RDM_OID_QOS_QUE                          88548	/*Device.QoS.Queue.i*/
#define RDM_OID_QOS_QUE_STAT                     89088	/*Device.QoS.QueueStats.i*/
#define RDM_OID_QOS_SHAPER                       89388	/*Device.QoS.Shaper.i*/
#define RDM_OID_LAN_CONF_SEC                     89568	/*Device.LANConfigSecurity*/
#define RDM_OID_HOSTS                            89628	/*Device.Hosts*/
#define RDM_OID_HOSTS_HOST                       89712	/*Device.Hosts.Host.i*/
#define RDM_OID_HOSTS_HOST_V4_ADDR               90684	/*Device.Hosts.Host.i.IPv4Address.i*/
#define RDM_OID_HOSTS_HOST_V6_ADDR               90744	/*Device.Hosts.Host.i.IPv6Address.i*/
#define RDM_OID_ZY_HOSTS_HOST_EXT                90804	/*Device.Hosts.Host.i.X_ZYXEL_EXT*/
#define RDM_OID_DNS                              91104	/*Device.DNS*/
#define RDM_OID_DNS_CLIENT                       91260	/*Device.DNS.Client*/
#define RDM_OID_DNS_CLIENT_SRV                   91392	/*Device.DNS.Client.Server.i*/
#define RDM_OID_DNS_RELAY                        91668	/*Device.DNS.Relay*/
#define RDM_OID_DNS_RELAY_FWD                    91800	/*Device.DNS.Relay.Forwarding.i*/
#define RDM_OID_DNS_DIAG                         91980	/*Device.DNS.Diagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG          92016	/*Device.DNS.Diagnostics.NSLookupDiagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG_RESULT   92268	/*Device.DNS.Diagnostics.NSLookupDiagnostics.Result.i*/
#define RDM_OID_NAT                              92448	/*Device.NAT*/
#define RDM_OID_NAT_INTF_SETTING                 92724	/*Device.NAT.InterfaceSetting.i*/
#define RDM_OID_NAT_PORT_MAPPING                 92880	/*Device.NAT.PortMapping.i*/
#define RDM_OID_NAT_PORT_TRIGGERING              93396	/*Device.NAT.X_ZYXEL_PortTriggering.i*/
#define RDM_OID_NAT_ADDR_MAPPING                 93720	/*Device.NAT.X_ZYXEL_AddrMapping.i*/
#define RDM_OID_NAT_SESSION_CTL                  94044	/*Device.NAT.X_ZYXEL_SessionControl*/
#define RDM_OID_DHCPV4                           94224	/*Device.DHCPv4*/
#define RDM_OID_DHCPV4_CLIENT                    94284	/*Device.DHCPv4.Client.i*/
#define RDM_OID_DHCPV4_SENT_OPT                  94752	/*Device.DHCPv4.Client.i.SentOption.i*/
#define RDM_OID_DHCPV4_REQ_OPT                   94884	/*Device.DHCPv4.Client.i.ReqOption.i*/
#define RDM_OID_DHCPV4_SRV                       95040	/*Device.DHCPv4.Server*/
#define RDM_OID_DHCPV4_SRV_POOL                  95148	/*Device.DHCPv4.Server.Pool.i*/
#define RDM_OID_DHCPV4_SRV_POOL_STATIC_ADDR      96000	/*Device.DHCPv4.Server.Pool.i.StaticAddress.i*/
#define RDM_OID_DHCPV4_SRV_POOL_OPT              96132	/*Device.DHCPv4.Server.Pool.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT           96264	/*Device.DHCPv4.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_V4_ADDR   96420	/*Device.DHCPv4.Server.Pool.i.Client.i.IPv4Address.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_OPT       96504	/*Device.DHCPv4.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_SUBNET                96588	/*Device.DHCPv4.Server.X_ZYXEL_Subnet.i*/
#define RDM_OID_DHCPV4_RELAY                     96768	/*Device.DHCPv4.Relay*/
#define RDM_OID_DHCPV4_RELAY_FWD                 96876	/*Device.DHCPv4.Relay.Forwarding.i*/
#define RDM_OID_DHCPV6                           97320	/*Device.DHCPv6*/
#define RDM_OID_DHCPV6_CLIENT                    97380	/*Device.DHCPv6.Client.i*/
#define RDM_OID_DHCPV6_CLIENT_SRV                97824	/*Device.DHCPv6.Client.i.Server.i*/
#define RDM_OID_DHCPV6_CLIENT_SENT_OPT           97932	/*Device.DHCPv6.Client.i.SentOption.i*/
#define RDM_OID_DHCPV6_CLIENT_RECEIVED_OPT       98064	/*Device.DHCPv6.Client.i.ReceivedOption.i*/
#define RDM_OID_DHCPV6_SRV                       98172	/*Device.DHCPv6.Server*/
#define RDM_OID_DHCPV6_SRV_POOL                  98256	/*Device.DHCPv6.Server.Pool.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT           99012	/*Device.DHCPv6.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_ADDR   99192	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Address.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_PREFIX 99300	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Prefix.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_OPT       99408	/*Device.DHCPv6.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV6_SRV_POOL_OPT              99492	/*Device.DHCPv6.Server.Pool.i.Option.i*/
#define RDM_OID_IEEE8021X                        99648	/*Device.IEEE8021x*/
#define RDM_OID_IEEE8021X_SUPPLICANT             99708	/*Device.IEEE8021x.Supplicant.i*/
#define RDM_OID_IEEE8021X_SUPPLICANT_STAT        100176	/*Device.IEEE8021x.Supplicant.i.Stats*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPMD5      100476	/*Device.IEEE8021x.Supplicant.i.EAPMD5*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPTLS      100560	/*Device.IEEE8021x.Supplicant.i.EAPTLS*/
#define RDM_OID_USRS                             100644	/*Device.Users*/
#define RDM_OID_USRS_USR                         100704	/*Device.Users.User.i*/
#define RDM_OID_SMART_CARD_READERS               100884	/*Device.SmartCardReaders*/
#define RDM_OID_SMART_CARD_READERS_SCR           100944	/*Device.SmartCardReaders.SmartCardReader.i*/
#define RDM_OID_SMART_CARD_READERS_SCR_SC        101172	/*Device.SmartCardReaders.SmartCardReader.i.SmartCard*/
#define RDM_OID_UPNP                             101328	/*Device.UPnP*/
#define RDM_OID_UPNP_DEV                         101364	/*Device.UPnP.Device*/
#define RDM_OID_UPNP_DEV_CAPB                    101688	/*Device.UPnP.Device.Capabilities*/
#define RDM_OID_UPNP_DISC                        102012	/*Device.UPnP.Discovery*/
#define RDM_OID_UPNP_DISC_ROOT_DEV               102120	/*Device.UPnP.Discovery.RootDevice.i*/
#define RDM_OID_UPNP_DISC_DEV                    102324	/*Device.UPnP.Discovery.Device.i*/
#define RDM_OID_UPNP_DISC_SERVICE                102528	/*Device.UPnP.Discovery.Service.i*/
#define RDM_OID_DLNA                             102708	/*Device.DLNA*/
#define RDM_OID_DLNA_CAPB                        102888	/*Device.DLNA.Capabilities*/
#define RDM_OID_SELF_TEST_DIAG                   103116	/*Device.SelfTestDiagnostics*/
#define RDM_OID_FIREWALL                         103200	/*Device.Firewall*/
#define RDM_OID_FIREWALL_LEVEL                   103524	/*Device.Firewall.Level.i*/
#define RDM_OID_FIREWALL_CHAIN                   103776	/*Device.Firewall.Chain.i*/
#define RDM_OID_FIREWALL_CHAIN_RULE              103932	/*Device.Firewall.Chain.i.Rule.i*/
#define RDM_OID_PERD_STATISTICS                  104976	/*Device.PeriodicStatistics*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET       105084	/*Device.PeriodicStatistics.SampleSet.i*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET_PARAM 105432	/*Device.PeriodicStatistics.SampleSet.i.Parameter.i*/
#define RDM_OID_SW_MODULE                        105732	/*Device.SoftwareModules*/
#define RDM_OID_SW_MODULE_EXEC_ENV               105840	/*Device.SoftwareModules.ExecEnv.i*/
#define RDM_OID_SW_MODULE_DEPLOYMENT_UNIT        106332	/*Device.SoftwareModules.DeploymentUnit.i*/
#define RDM_OID_SW_MODULE_EXEC_UNIT              106704	/*Device.SoftwareModules.ExecutionUnit*/
#define RDM_OID_SW_MODULE_EXEC_UNIT_EXT          107244	/*Device.SoftwareModules.ExecutionUnit.Extensions*/
#define RDM_OID_FAULT_MGMT                       107280	/*Device.FaultMgmt*/
#define RDM_OID_FAULT_MGMT_SUPT_ALARM            107460	/*Device.FaultMgmt.SupportedAlarm.i*/
#define RDM_OID_FAULT_MGMT_CURRENT_ALARM         107616	/*Device.FaultMgmt.CurrentAlarm.i*/
#define RDM_OID_FAULT_MGMT_HISTORY_EVENT         107892	/*Device.FaultMgmt.HistoryEvent.i*/
#define RDM_OID_FAULT_MGMT_EXPEDITED_EVENT       108168	/*Device.FaultMgmt.ExpeditedEvent.i*/
#define RDM_OID_FAULT_MGMT_QUED_EVENT            108444	/*Device.FaultMgmt.QueuedEvent.i*/
#define RDM_OID_DEV_SEC                          108720	/*Device.Security*/
#define RDM_OID_DEV_SEC_CERT                     108780	/*Device.Security.Certificate.i*/
#define RDM_OID_FAP                              109248	/*Device.FAP*/
#define RDM_OID_FAP_GPS                          109284	/*Device.FAP.GPS*/
#define RDM_OID_FAP_GPS_CONTS_GPS_STATUS         109656	/*Device.FAP.GPS.ContinuousGPSStatus*/
#define RDM_OID_FAP_GPS_AGPS_SRV_CONF            110028	/*Device.FAP.GPS.AGPSServerConfig*/
#define RDM_OID_FAP_PERF_MGMT                    110256	/*Device.FAP.PerfMgmt*/
#define RDM_OID_FAP_PERF_MGMT_CONF               110316	/*Device.FAP.PerfMgmt.Config.i*/
#define RDM_OID_FAP_APP_PLATF                    110520	/*Device.FAP.ApplicationPlatform*/
#define RDM_OID_FAP_APP_PLATF_CAPB               110676	/*Device.FAP.ApplicationPlatform.Capabilities*/
#define RDM_OID_FAP_APP_PLATF_CTRL               111024	/*Device.FAP.ApplicationPlatform.Control*/
#define RDM_OID_FAP_APP_PLATF_CTRL_FEMTO_AWARE   111108	/*Device.FAP.ApplicationPlatform.Control.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_CTRL_SMS           111336	/*Device.FAP.ApplicationPlatform.Control.SMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_MMS           111540	/*Device.FAP.ApplicationPlatform.Control.MMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_TERM_LOC      111744	/*Device.FAP.ApplicationPlatform.Control.TerminalLocation*/
#define RDM_OID_FAP_APP_PLATF_MONT               111972	/*Device.FAP.ApplicationPlatform.Monitoring*/
#define RDM_OID_FAP_APP_PLATF_MONT_FEMTO_AWARE   112104	/*Device.FAP.ApplicationPlatform.Monitoring.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_MONT_SMS           112284	/*Device.FAP.ApplicationPlatform.Monitoring.SMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_MMS           112464	/*Device.FAP.ApplicationPlatform.Monitoring.MMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_TERM_LOC      112644	/*Device.FAP.ApplicationPlatform.Monitoring.TerminalLocation*/
#define RDM_OID_BULK_DATA                        112824	/*Device.BulkData*/
#define RDM_OID_BULK_DATA_PROF                   113052	/*Device.BulkData.Profile.i*/
#define RDM_OID_BULK_DATA_PROF_PARAM             113424	/*Device.BulkData.Profile.i.Parameter.i*/
#define RDM_OID_ROM_CONVERT                      113484	/*Device.X_ZYXEL_RomConvert.i*/
#define RDM_OID_SCHEDULE                         113544	/*Device.X_ZYXEL_Schedule.i*/
#define RDM_OID_EMAIL_NOTIFY                     113820	/*Device.X_ZYXEL_EmailNotification*/
#define RDM_OID_MAIL_SERVICE                     113856	/*Device.X_ZYXEL_EmailNotification.EmailService.i*/
#define RDM_OID_MAIL_EVENT_CFG                   114084	/*Device.X_ZYXEL_EmailNotification.EmailEventConfig.i*/
#define RDM_OID_PAREN_CTL                        114264	/*Device.X_ZYXEL_ParentalControl*/
#define RDM_OID_PAREN_CTL_PROF                   114324	/*Device.X_ZYXEL_ParentalControl.Profile.i*/
#define RDM_OID_IEEE8021AG                       114648	/*Device.X_ZYXEL_8021ag*/
#define RDM_OID_IEEE8023AH                       115140	/*Device.X_ZYXEL_8023ah*/
#define RDM_OID_ZY_EXT                           115392	/*Device.X_ZYXEL_EXT*/
#define RDM_OID_DNS_RT_ENTRY                     115500	/*Device.X_ZYXEL_EXT.DNSRouteEntry.i*/
#define RDM_OID_DNS_ENTRY                        115728	/*Device.X_ZYXEL_EXT.DNSEntry.i*/
#define RDM_OID_D_DNS                            115812	/*Device.X_ZYXEL_EXT.DynamicDNS*/
#define RDM_OID_AUTO_PROV                        116232	/*Device.X_ZYXEL_EXT.AutoProvision*/
#define RDM_OID_SPEED_TEST                       116460	/*Device.X_ZYXEL_EXT.SpeedTestInfo*/
#define RDM_OID_WIFI_QSTEER                      116568	/*Device.X_ZYXEL_EXT.Qsteer*/
#define RDM_OID_ZY_HOST_NAME_REPLACE             116700	/*Device.X_ZYXEL_EXT.HostNameReplace*/
#define RDM_OID_PPTP_CFG                         116760	/*Device.X_ZYXEL_EXT.X_ZYXEL_PPTP_Config*/
#define RDM_OID_EOGRE_CFG                        117060	/*Device.X_ZYXEL_EXT.X_ZYXEL_EoGRE_Config*/
#define RDM_OID_LAN_DEV                          117240	/*Device.X_ZYXEL_EXT.LANDevice.i*/
#define RDM_OID_EASY_MESH                        117348	/*Device.X_ZYXEL_EXT.EasyMesh*/
#define RDM_OID_MAC_ADDRESS_TABLE                117408	/*Device.X_ZYXEL_EXT.MacAddressTable*/
#define RDM_OID_ZY_IGMP                          117588	/*Device.X_ZYXEL_IGMP*/
#define RDM_OID_ZY_SNMP                          118080	/*Device.X_ZYXEL_SNMP*/
#define RDM_OID_TRAP_ADDR                        118236	/*Device.X_ZYXEL_SNMP.TrapAddr.i*/
#define RDM_OID_ZY_MLD                           118344	/*Device.X_ZYXEL_MLD*/
#define RDM_OID_ZY_LOG_CFG                       118764	/*Device.X_ZYXEL_LoginCfg*/
#define RDM_OID_ZY_LOG_CFG_GP                    118872	/*Device.X_ZYXEL_LoginCfg.LogGp.i*/
#define RDM_OID_ZY_LOG_CFG_GP_ACCOUNT            119028	/*Device.X_ZYXEL_LoginCfg.LogGp.i.Account.i*/
#define RDM_OID_ZY_MAC_FILTER                    119856	/*Device.X_ZYXEL_MacFilter*/
#define RDM_OID_ZY_MAC_FILTER_WHITE_LIST         119964	/*Device.X_ZYXEL_MacFilter.WhiteList.i*/
#define RDM_OID_WLAN_SCHEDULER_ACCESS            120072	/*Device.X_ZYXEL_WlanSchedulerAccess*/
#define RDM_OID_VC_AUTO_HUNT                     120180	/*Device.X_ZYXEL_VcAutoHunt*/
#define RDM_OID_VC_HUNT_INFO                     120336	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i*/
#define RDM_OID_VC_HUNT_RULE                     120420	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i.VcHuntRule.i*/
#define RDM_OID_VLAN_AUTO_HUNT                   120504	/*Device.X_ZYXEL_VlanAutoHunt*/
#define RDM_OID_VLAN_HUNT_INFO                   120636	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i*/
#define RDM_OID_VLAN_HUNT_RULE                   120720	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i.VlanHuntRule.i*/
#define RDM_OID_LANG                             120804	/*Device.X_ZYXEL_Language*/
#define RDM_OID_REMO_MGMT                        120864	/*Device.X_ZYXEL_RemoteManagement*/
#define RDM_OID_REMO_SRV                         120972	/*Device.X_ZYXEL_RemoteManagement.Service.i*/
#define RDM_OID_REMO_SRV_TRUST_DOMAIN            121272	/*Device.X_ZYXEL_RemoteManagement.Service.i.TrustDomain.i*/
#define RDM_OID_SP_REMO_SRV                      121380	/*Device.X_ZYXEL_RemoteManagement.SPService.i*/
#define RDM_OID_SP_REMO_SRV_TRUST_DOMAIN         121680	/*Device.X_ZYXEL_RemoteManagement.SPService.i.TrustDomain.i*/
#define RDM_OID_REMO_MGMT_TRUST_DOMAIN           121812	/*Device.X_ZYXEL_RemoteManagement.TrustDomain.i*/
#define RDM_OID_SP_TRUST_DOMAIN                  121920	/*Device.X_ZYXEL_RemoteManagement.SPTrustDomain.i*/
#define RDM_OID_NETWORK_SRV                      122052	/*Device.X_ZYXEL_NetworkService*/
#define RDM_OID_NETWORK_SRV_GP                   122112	/*Device.X_ZYXEL_NetworkService.Service.i*/
#define RDM_OID_SYSTEM_INFO                      122364	/*Device.X_ZYXEL_System_Info*/
#define RDM_OID_GPON_INFO                        122640	/*Device.X_ZYXEL_GPON_Info*/
#define RDM_OID_LOG_SETTING                      122844	/*Device.X_ZYXEL_Log_Setting*/
#define RDM_OID_LOG_CLASSIFY                     123048	/*Device.X_ZYXEL_Log_Setting.LogClassify.i*/
#define RDM_OID_LOG_CATEGORY                     123156	/*Device.X_ZYXEL_Log_Setting.LogClassify.i.Category.i*/
#define RDM_OID_CHANGE_ICON_NAME                 123336	/*Device.X_ZYXEL_Change_Icon_Name.i*/
#define RDM_OID_PORT_MIRROR                      123660	/*Device.X_ZYXEL_PortMirroring.i*/
#define RDM_OID_VLAN_GROUP                       123792	/*Device.X_ZYXEL_VlanGroup.i*/
#define RDM_OID_S_T_B_VENDOR_I_D                 123972	/*Device.X_ZYXEL_STB_VENDOR_ID*/
#define RDM_OID_T_F_T_P_SRV_NAME                 124128	/*Device.X_ZYXEL_TFTP_SERVER_NAME*/
#define RDM_OID_TR064                            124188	/*Device.X_ZYXEL_TR064*/
#define RDM_OID_ACL                              124368	/*Device.X_ZYXEL_TR064.ACL*/
#define RDM_OID_CONTROL_POINT                    124404	/*Device.X_ZYXEL_TR064.ACL.CP.i*/
#define RDM_OID_ACTIONS                          124536	/*Device.X_ZYXEL_TR064.ACL.Actions.i*/
#define RDM_OID_ZY_W_W_A_N_BACKUP                124644	/*Device.X_ZYXEL_WWAN_BACKUP*/
#define RDM_OID_ZY_W_W_A_N_PING_CHECK            125088	/*Device.X_ZYXEL_WWAN_BACKUP.PingCheck*/
#define RDM_OID_ZY_W_W_A_N_BUDGET_CONTROL        125244	/*Device.X_ZYXEL_WWAN_BACKUP.BudgetControl*/
#define RDM_OID_ZY_W_W_A_N_STAT                  125928	/*Device.X_ZYXEL_WWAN_BACKUP.Stats*/
#define RDM_OID_ZY_SAMBA                         126180	/*Device.X_ZYXEL_SAMBA*/
#define RDM_OID_ZY_SAMBA_DIR                     126288	/*Device.X_ZYXEL_SAMBA.Directory.i*/
#define RDM_OID_GUI_CUSTOMIZATION                126540	/*Device.X_ZYXEL_GUI_CUSTOMIZATION*/
#define RDM_OID_INPUT_CHECK_LIST                 126984	/*Device.X_ZYXEL_GUI_CUSTOMIZATION.InputCheckList.i*/
#define RDM_OID_FEATURE_FLAG                     127164	/*Device.X_ZYXEL_FEATRUE_FLAG*/
#define RDM_OID_ZY_OPTION125                     127584	/*Device.X_ZYXEL_Option125VendorSpecific*/
#define RDM_OID_ZY_VENDOR_SPECIFIC               127644	/*Device.X_ZYXEL_Option125VendorSpecific.VendorSpecific.i*/
#define RDM_OID_ZY_IPP_CFG                       127776	/*Device.X_ZYXEL_Ipp_Cfg*/
#define RDM_OID_GPON                             127908	/*Device.X_ZYXEL_GPON*/
#define RDM_OID_ONU                              127944	/*Device.X_ZYXEL_GPON.ONU*/
#define RDM_OID_ANI                              128652	/*Device.X_ZYXEL_GPON.ANI*/
#define RDM_OID_OLT                              129120	/*Device.X_ZYXEL_GPON.OLT*/
#define RDM_OID_CAPABILITY                       129252	/*Device.X_ZYXEL_GPON.Capability*/
#define RDM_OID_LOIDAUTH                         129360	/*Device.X_ZYXEL_GPON.LOIDAuth*/
#define RDM_OID_SOFTIMAGE                        129468	/*Device.X_ZYXEL_GPON.SoftImage.i*/
#define RDM_OID_PM                               129600	/*Device.X_ZYXEL_GPON.PM*/
#define RDM_OID_COMMON                           129756	/*Device.X_ZYXEL_GPON.Common*/
#define RDM_OID_XPON                             129840	/*Device.X_ZYXEL_GPON.Xpon*/
#define RDM_OID_LINKCFG                          129996	/*Device.X_ZYXEL_GPON.LinkCfg*/
#define RDM_OID_IPHOST                           130080	/*Device.X_ZYXEL_GPON.IPHost*/
#define RDM_OID_OMCI_CFG                         130164	/*Device.X_ZYXEL_GPON.OmciConfig*/
#define RDM_OID_OMCI                             130200	/*Device.X_ZYXEL_GPON.OmciConfig.Omci*/
#define RDM_OID_GEMPORT                          130404	/*Device.X_ZYXEL_GPON.OmciConfig.GEMPort*/
#define RDM_OID_TCONT                            130560	/*Device.X_ZYXEL_GPON.OmciConfig.TCONT*/
#define RDM_OID_TRTCM                            130644	/*Device.X_ZYXEL_GPON.OmciConfig.Trtcm*/
#define RDM_OID_QOSCFG                           130800	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg*/
#define RDM_OID_QOS_VALUE                        130980	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg.QOSValue.i*/
#define RDM_OID_CNGSTCFG                         131040	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg*/
#define RDM_OID_CONGEST_THRED_VALUE              131268	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg.CongestThredValue.i*/
#define RDM_OID_TRTCMCFG                         131328	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg*/
#define RDM_OID_TRTCM_VALUE                      131460	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg.TrtcmValue.i*/
#define RDM_OID_QUEUE                            131520	/*Device.X_ZYXEL_GPON.OmciConfig.Queue*/
#define RDM_OID_ONT_GENERIC                      131580	/*Device.X_ZYXEL_GPON.OntGeneric*/
#define RDM_OID_ZY_ONE_CONNECT                   131640	/*Device.X_ZYXEL_OneConnect*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_MASTER_SWITCH 131748	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_RULE 131832	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter.Rule.i*/
#define RDM_OID_ONE_CONNECT_P_C_GENERAL          131964	/*Device.X_ZYXEL_OneConnect_Parental_Control*/
#define RDM_OID_ONE_CONNECT_P_C_RULE             132072	/*Device.X_ZYXEL_OneConnect_Parental_Control.Rule.i*/
#define RDM_OID_ONLINE_F_W_UPGRADE               132348	/*Device.X_ZYXEL_Online_FW_Upgrade*/
#define RDM_OID_LANDING_PAGE                     132600	/*Device.X_ZYXEL_Landing_Page*/
#define RDM_OID_POWER_MGMT                       132684	/*Device.X_ZYXEL_Power_Management*/
#define RDM_OID_POWER_SCHEDULE                   133080	/*Device.X_ZYXEL_Power_Management.PowerSchedule.i*/
#define RDM_OID_ZY_LOOP_GUARD                    133236	/*Device.X_ZYXEL_LOOP_GUARD*/
#define RDM_OID_ZY_PROXIMITY_SENSOR              133344	/*Device.X_ZYXEL_PROXIMITY_SENSOR*/
#define RDM_OID_ZY_SFP_MANAGEMENT                133404	/*Device.X_ZYXEL_SFP_Management*/
#define RDM_OID_ZY_RESET_ADMIN                   133488	/*Device.X_ZYXEL_RESET_ADMIN*/
#define RDM_OID_OI_WIZARD                        133548	/*Device.X_ZYXEL_OiWizard*/
#define RDM_OID_ZY_DATA_USAGE                    133752	/*Device.X_ZYXEL_DataUsage*/
#define RDM_OID_ZY_DATA_USAGE_LAN                133812	/*Device.X_ZYXEL_DataUsage.Lan.i*/
#define RDM_OID_ZY_DATA_USAGE_WAN                133920	/*Device.X_ZYXEL_DataUsage.Wan.i*/
#define RDM_OID_IPERF                            134028	/*Device.X_TELECOMITALIA_IT_Iperf*/
#define RDM_OID_ZLOG_CONFIG                      134160	/*Device.X_ZYXEL_Zlog_Setting*/
#define RDM_OID_ZLOG_CATEGORY                    134244	/*Device.X_ZYXEL_Zlog_Setting.ZlogCategory.i*/
#define RDM_OID_HOME_CYBER_SECURITY              134592	/*Device.X_ZYXEL_HomeCyberSecurity*/
#define RDM_OID_CONTENT_FILTER                   134748	/*Device.X_ZYXEL_ContentFilter.i*/
#define RDM_OID_U_R_L_FILTER                     135240	/*Device.X_ZYXEL_URLFilter.i*/
#define RDM_OID_WHITE_U_R_L_FILTER               135372	/*Device.X_ZYXEL_URLFilter.i.WhiteList.i*/
#define RDM_OID_BLACK_U_R_L_FILTER               135480	/*Device.X_ZYXEL_URLFilter.i.BlackList.i*/
#define RDM_OID_ZY_LICNSE                        135588	/*Device.X_ZYXEL_License*/
#define RDM_OID_MOS                              135648	/*Device.X_ZYXEL_Mos*/
#define RDM_OID_MOS_USR_CFG                      135684	/*Device.X_ZYXEL_Mos.MosUserConfig*/
#define RDM_OID_OMCI_VLAN_INFO                   137376	/*Device.X_ZYXEL_Mos.OmciVlanInfo.i*/

#define RDM_OID_MAX                   137652     // for OID validation

#define RDM_OID_IS_INVALID(_oid_)    ((_oid_ < 0) || (_oid_ >= RDM_OID_MAX))

#endif // _ZCFG_RDM_OID_H
