#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

echo "ext_ifname=eth4.4" >/tmp/miniupnpd.conf
echo "listening_ip=192.168.1.1" >>/tmp/miniupnpd.conf
echo "port=5000" >>/tmp/miniupnpd.conf
echo "enable_natpmp=yes" >>/tmp/miniupnpd.conf
echo "enable_upnp=yes" >>/tmp/miniupnpd.conf
echo "secure_mode=no" >>/tmp/miniupnpd.conf
echo "system_uptime=yes" >>/tmp/miniupnpd.conf
uuid="$(cat /proc/sys/kernel/random/uuid | cut -c 1-24)"
MAC="$(ifconfig br0 | grep HWaddr|awk -F ' ' '{print $5}'|sed 's/://g' | tr A-Z a-z)"
echo "uuid=$uuid$MAC" >>/tmp/miniupnpd.conf
#serial_num=$(cat /tmp/Serial_num)
echo "serial=N/A" >>/tmp/miniupnpd.conf
echo "allow 1024-65535 0.0.0.0/0 1024-65535" >>/tmp/miniupnpd.conf
/usr/sbin/miniupnpd -f /tmp/miniupnpd.conf
	
